--- USU�RIO
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO (
    ID NUMBER(10) PRIMARY KEY,
    EMAIL_CORPORATIVO VARCHAR2(150) NOT NULL UNIQUE,
    NOME VARCHAR2(120) NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    TIPO NUMBER(3) NOT NULL,
    
    CONSTRAINT CK_USUARIO_TIPO
        CHECK (TIPO BETWEEN 0 AND 10)
);

--- QUESTION�RIO
CREATE SEQUENCE SEQ_QUESTIONARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE QUESTIONARIO (
    ID NUMBER(10) PRIMARY KEY,
    DATA_PREENCHIMENTO DATE NOT NULL,
    NIVEL_ESTRESSE NUMBER(3) NOT NULL CHECK (NIVEL_ESTRESSE BETWEEN 0 AND 10),
    QUALIDADE_SONO NUMBER(3) NOT NULL CHECK (QUALIDADE_SONO BETWEEN 0 AND 10),
    ANSIEDADE NUMBER(3) NOT NULL CHECK (ANSIEDADE BETWEEN 0 AND 10),
    SOBRECARGA NUMBER(3) NOT NULL CHECK (SOBRECARGA BETWEEN 0 AND 10),
    AVALIACAO VARCHAR2(300) NOT NULL,

    USUARIO_ID NUMBER(10) NOT NULL,
    
    CONSTRAINT FK_QUESTIONARIO_USUARIO
        FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID)
        ON DELETE CASCADE
);